// <auto-generated />
namespace BlockByBlock.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Mtc_Activity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mtc_Activity));
        
        string IMigrationMetadata.Id
        {
            get { return "201809232201467_Mtc_Activity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
